'use client';
import Link from 'next/link';
import { useState } from 'react';
import { POLICY_VERSION, PROFILE_COPY } from '@/lib/copy/profile-onboarding';
import { validateRut } from '@/lib/profile/rut';
export default function OnboardingFlow({ copy }: { copy: typeof PROFILE_COPY }) {
  const [rut,setRut]=useState(''); const [pn,setPn]=useState(false); const [step,setStep]=useState<'landing'|'loading'|'aha'|'gate'|'refine'|'radar'>('landing'); const [data,setData]=useState<any>(null); const [error,setError]=useState(''); const [policy,setPolicy]=useState(false); const [digest,setDigest]=useState(false);
  async function lookup(){ setError(''); if(!validateRut(rut)){setError(copy.errors.invalidRut); return;} setStep('loading'); const started=Date.now(); const res=await fetch('/api/profile/lookup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rut,is_natural_person:pn,session_id:getSession()})}).catch(()=>null); const wait=Math.max(0,1500-(Date.now()-started)); setTimeout(async()=>{ if(!res){setData({fallback:true,n_matches_hoy:0});setStep('aha');return;} if(!res.ok){setError((await res.json()).error ?? copy.errors.timeout);setStep('landing');return;} setData(await res.json()); setStep('aha');},wait); }
  function signup(e: React.FormEvent){ e.preventDefault(); if(!policy){setError(copy.gate.blocked);return;} setStep(data?.tier==='delgado'?'refine':'radar'); void fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'signup_completed',session_id:getSession(),payload:{policy_version_accepted:POLICY_VERSION,policy_accepted_at:new Date().toISOString(),digest_enabled:digest}})}); }
  return <main className="shell"><header><strong>{copy.landing.title}</strong><Link href="/login">{copy.landing.login}</Link></header>{step==='landing'&&<section className="card"><h1>{copy.landing.rutLabel}</h1><p>{copy.landing.rutHelp}</p><label htmlFor="rut">{copy.landing.rutLabel}</label><input id="rut" value={rut} onChange={e=>setRut(e.target.value)} aria-describedby="rut-help rut-error" placeholder={copy.landing.rutExample}/><p id="rut-help">{copy.landing.rutExample}</p>{error&&<p id="rut-error" role="alert">{error}</p>}<fieldset><legend>{copy.landing.title}</legend><button type="button" aria-pressed={!pn} onClick={()=>setPn(false)}>🏢 {copy.landing.company}</button><button type="button" aria-pressed={pn} onClick={()=>setPn(true)}>👤 {copy.landing.naturalPerson}</button></fieldset><button onClick={lookup}>{copy.landing.continue}</button></section>}{step==='loading'&&<section className="card" aria-live="polite">{copy.loading.map(t=><p className="reveal" key={t}>{t}</p>)}</section>}{step==='aha'&&<section className="card"><h1>{data?.oc_count_24m!=null? <>{copy.aha.soldPrefix} <span className="score">{data.oc_count_24m}</span> {copy.aha.soldSuffix}</>: copy.branches.declarative}</h1>{data?.fallback&&<p>{copy.branches.mirrorFallback}</p>}{pn&&<p>{copy.aha.pnTitle}</p>}<ul>{(data?.rubros_top3??data?.rubros_genericos??[]).map((r:string)=><li key={r}>✓ {r}</li>)}</ul>{data?.regiones?.map((r:string)=><span className="chip" key={r}>{r}</span>)}<p>{copy.aha.noAgainst}</p><h2><span className="score">{data?.n_matches_hoy??0}</span> {copy.aha.tendersSuffix}</h2>{data?.teaser?.top2?.map((t:any)=><article className="teaser" key={t.nombre_tender}><h3>{t.nombre_tender}</h3><p>{t.linea_justificacion}</p></article>)}<div className="blur" aria-hidden="true"><p>{copy.errors.hiddenTender}</p></div><button onClick={()=>setStep('gate')}>{copy.gate.titlePrefix} {data?.n_matches_hoy??0}</button></section>}{step==='gate'&&<form className="card" onSubmit={signup}><h1>{copy.gate.titlePrefix} {data?.n_matches_hoy??0}</h1><label>{copy.gate.emailLabel}<input type="email" required /></label><label><input type="checkbox" checked={policy} onChange={e=>setPolicy(e.target.checked)}/>{copy.gate.privacy}</label><label><input type="checkbox" checked={digest} onChange={e=>setDigest(e.target.checked)}/>{copy.gate.digest}</label>{error&&<p role="alert">{error}</p>}<button>{copy.gate.cta}</button></form>}{step==='refine'&&<section className="card"><h1>{copy.refine.title}</h1>{data?.tier==='delgado'&&<p>{copy.refine.thin}</p>}<button onClick={()=>setStep('radar')}>{copy.refine.cta}</button>{data?.tier!=='delgado'&&<button onClick={()=>setStep('radar')}>{copy.refine.skip}</button>}</section>}{step==='radar'&&<section className="card"><h1>{copy.errors.radar}</h1><p>{copy.aha.noAgainst}</p></section>}<footer>{copy.footer.text} · <Link href="/politica-privacidad">{copy.footer.privacy}</Link> · <Link href="/tus-datos">{copy.footer.data}</Link></footer></main> }
function getSession(){ let id=sessionStorage.getItem('conviene_session_id'); if(!id){id=crypto.randomUUID();sessionStorage.setItem('conviene_session_id',id)} return id; }
